#Inspirations: https://github.com/dzlab/dzlab.github.io/blob/master/_config.yml

#Setup
title:        Marcel Castro
tagline:      'Machine Learning'
email:        marcelcastrobr@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal site to capture my path in Machine Learning.
baseurl:      /
url:          https://marcelcastrobr.github.io
markdown: kramdown

# twitter_username: jekyllrb
github_username:  marcelcastrobr

author:
  name:     'marcelcastrobr'
  
  
paginate:   10

#google_analytics: UA-128961990-1

github:
  repo:           https://github.com/marcelcastrobr


# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-toc
  - jekyll-paginate
