project:
  type: website
  output-dir: docs

website:
  title: "Marcel Castro"
  navbar:
    background: primary
    search: true
    left: 
      - text: Notes
        href: https://github.com/marcelcastrobr/my_ml_notes
      - text: Notebooks
        file: index.qmd
      - about.qmd
      - text: Links
        href: https://marcelcastrobr.github.io/my_ml_links/
    right:
      - icon: bi-filetype-pdf
        href: https://github.com/marcelcastrobr/marcelcastrobr.github.io/blob/main/cv/cv-marcelcastro.pdf
      - icon: bi-diagram-3-fill
        href: https://marcelcastrobr.github.io/my_ml_links/
      - icon: emoji-smile
        href: https://huggingface.co/marcelcastrobr
      - icon: github
        href: https://github.com/marcelcastrobr
      - icon: linkedin
        href: https://www.linkedin.com/in/marcelcastrobr/
  page-footer: "Copyright 2023, Marcel Castro" 
  reader-mode: true
  google-analytics: "G-RK1QNXR9TB"
  #repo-url: https://github.com/marcelcastrobr/quarto_notebooks
  #repo-actions: [edit, issue]
format:
  html:
    theme: default
    css: styles.css


